//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAcceptanceGraphTraversal.GraphTraversal {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GraphTraversal.IGraphTraversal")]
    public interface IGraphTraversal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraphTraversal/Traverse", ReplyAction="http://tempuri.org/IGraphTraversal/TraverseResponse")]
        string Traverse();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGraphTraversalChannel : TestAcceptanceGraphTraversal.GraphTraversal.IGraphTraversal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GraphTraversalClient : System.ServiceModel.ClientBase<TestAcceptanceGraphTraversal.GraphTraversal.IGraphTraversal>, TestAcceptanceGraphTraversal.GraphTraversal.IGraphTraversal {
        
        public GraphTraversalClient() {
        }
        
        public GraphTraversalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GraphTraversalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GraphTraversalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GraphTraversalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Traverse() {
            return base.Channel.Traverse();
        }
    }
}
